stats = {
    "% of Earth's surface that is covered by water": 71,
    "% of Earth's water that is salt water": 97,
    "% of Earth's atmosphere that is Nitrogen": 78,
    "% of Earth's atmosphere that is Oxygen": 21,
    "% of Earth's land area covered by forests": 31,
    "% of the ocean that remains unexplored": 80,
    "% of Antarctica covered by ice": 98,
    "% of the world's freshwater locked in glaciers/ice": 69,
    "% of the world's freshwater found in Lake Baikal": 20,
    "% of the Sahara Desert that is actually sand": 25,
    "% of volcanic activity that happens underwater": 80,
    "% of Earth's surface that is the Pacific Ocean": 30,
    "% of an adults human body that is water": 60,
    "% of the human brain that is water": 73,
    "% of human bones that are water": 31,
    "% of people who are right-handed": 90,
    "% of DNA humans share with a banana": 50,
    "% of the human body weight that is skin": 15,
    "% of adults who are lactose intolerant": 65,
    "% of height determined by genetics": 80,
    "% of human genome that is non-coding": 98,
    "% of people with the photic sneeze reflex": 25,
    "% of the human skeleton found in the feet": 25,
    "% of blood that is plasma": 55,
    "% of the world population living in the Northern Hemisphere": 90,
    "% of the world population with internet access": 67,
    "% of the global population that is literate": 86,
    "% of the world population living in cities": 56,
    "% of people who dream in color": 88,
    "% of people with blue eyes globally": 9,
    "% of people with brown eyes globally": 75,
    "% of the world population living in Asia": 60,
    "% of people who can roll their tongue": 70,
    "% of the world population under age 15": 25,
    "% of the global population that has a smartphone": 85,
    "% of households with a TV globally": 79,
    "% of a jellyfish that is water": 95,
    "% of a cucumber that is water": 95,
    "% of a watermelon that is water": 92,
    "% of a cat's life spent sleeping": 70,
    "% of a giant panda's day spent eating": 58,
    "% of animal species that are insects": 80,
    "% of an apple that is actually air": 25,
    "% of the world's vanilla that is synthetic": 99,
    "% of the world's coffee produced by Brazil": 40,
    "% of the world's cork produced by Portugal": 50,
    "% of an egg's weight that is the shell": 10,
    "% of the Universe made of Normal Matter": 5,
    "% of the Universe made of Dark Energy": 68,
    "% of the moon's surface visible from Earth": 59,
    "% of global electricity that comes from renewables": 30,
    "% of global plastic ever produced that was recycled": 9,
    "% of global trade carried by sea": 80,
    "% of the atmosphere of Mars that is Carbon Dioxide": 95,
}